# Always validate the PR title, and ignore the commits
titleOnly: true

# Always validate all commits, and ignore the PR title
commitsOnly: false

# Always validate the PR title AND all the commits
titleAndCommits: false

# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: false
